language: java
jdk:
  - oraclejdk8


jobs:
  include:
    - stage: build
      install: ./gradlew setupCiWorkspace
      script: ./gradlew build 
    - stage: checkstyle
      script: ./gradlew checkstyle 

env:
  global:
    TERM=dumb
